apiVersion: v1
kind: ConfigMap
metadata:
  name: common-pod-config
#  namespace: client-apps
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"
  PASSWORD_ACCESS: "false"
#  USER_PASSWORD: Sks123
  USER_NAME: "linuxserver"
  SUDO_ACCESS: "true"
