{{- range .Values.image.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # हर डिप्लॉयमेंट का नाम अलग होगा (जैसे: release-ssh-pod-alpha)
  name: {{ $.Release.Name }}-{{ . }}
  labels:
    app: {{ $.Values.service.selector.app }}
    instance: {{ . }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.service.selector.app }}
      instance: {{ . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config_map.yaml") . | sha256sum }} 
      labels:
        app: {{ $.Values.service.selector.app }}
        instance: {{ . }}
    spec:
      initContainers:
        - name: init-myservice
          image: busybox
          envFrom:
            - configMapRef:
                name: common-pod-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "=== Preparing SSH home directory ==="
              mkdir -p /config/.ssh
              chown 1000:1000 /config/.ssh
              chmod 755 /config/.ssh
              cp /secret/authorized_keys /config/.ssh/authorized_keys
              chown 1000:1000 /config/.ssh
              chmod 700 /config/.ssh
              chown 1000:1000 /config/.ssh/authorized_keys
              chmod 600 /config/.ssh/authorized_keys
              echo "=== SSH authorized_keys installed ==="
          volumeMounts:
            - name: {{ $.Values.volumes.sshkeyvolume.name }}
              mountPath: /secret
              readOnly: true
            - name: {{ $.Values.volumes.emptydir.name }}
              mountPath: /config/.ssh/
      containers:
        - name: {{ . }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: common-pod-config
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
          volumeMounts:
            - name: {{ $.Values.volumes.emptydir.name }}
              mountPath: /config/.ssh
      volumes:
        - name: {{ $.Values.volumes.sshkeyvolume.name }}
          secret:
            secretName: {{ $.Values.volumes.sshkeyvolume.secretName }}
            items:
              - key: {{ (index $.Values.volumes.sshkeyvolume.items 0).key }}
                path: {{ (index $.Values.volumes.sshkeyvolume.items 0).path }}
                mode: 0600
        - name: {{ $.Values.volumes.emptydir.name }}
          emptyDir: {}
---
{{- end }}

