apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ssh-from-awx-client-app1
spec:
  podSelector:
    matchLabels:
      app: ssh
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: awx
      ports:
        - protocol: TCP
          port: 22
